### ISSUE TITLE
Data Type mapping compliance with R2DBC spec

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-spanner-r2dbc#100]
We need to ensure compliance with the data type mapping as [defined in the spec](https://r2dbc.io/spec/0.8.0.M8/spec/html/#datatypes), and recently amended in https://github.com/r2dbc/r2dbc-spi/pull/100.

If we are unable to comply with any of it, it should be documented.

**Comment by dmitry-s** [comment]
The only mapping that is not corresponding to the spec is java.sql.Timestamp for Spanner Timestamp type. The issue is Spanner's Timestamp supports only UTC and there is no good match in java.time
