### ISSUE TITLE
Documentation: Select vs DML vs DDL

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#113]
Document standard R2DBC treatment, explain that the driver will select the correct API to use.

Document the special `SpannerStatement` functionality that deviates from unified R2DBC treatment, when available.

**Comment by dzou** [comment]
@elefeint - Could you elaborate on this part:

> Document the special SpannerStatement functionality that deviates from unified R2DBC treatment, when available.

I forgot what this referred to.

**Comment by elefeint** [comment]
On statement:
* Lack of support for index binding
* explanation that the driver will pick one of 3 APIs (executeStreamingSql, batch update, DDL) depending on query content.

On connection:
* the custom transaction type override 
* lack of support for checkpoints.
