### ISSUE TITLE
Investigate autocommit for DML

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#119]
R2DBC's default behavior is autocommit.
Cloud Spanner's natural default behavior is a readonly transaction.

But @dzou had an idea that it is possible for us to support autocommit for autodetected DML statement type.

**Comment by ChengyuanZhao** [comment]
This is talking about the single-statement no-explicit-beginTransaction use case right ? (not the auto-commit if the user forgets to commitTransaction but did beginTransaction use case?)

**Comment by dzou** [comment]
Yup, it is to support if the user makes a DML query but omits the beginTransaction/commitTransaction stuff.
