### ISSUE TITLE
Bring in R2DBC SPI TCK

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#12]
https://github.com/r2dbc/r2dbc-spi/tree/master/r2dbc-spi-test

**Comment by ChengyuanZhao** [comment]
@elefeint 
I'm having trouble understanding what those classes are...  It looks like Example.java is the only class with tests but then there are tons of mock implementations of things. What are all those mock classes for?

**Comment by ChengyuanZhao** [comment]
The other thing is that those tests in Example.java all have DML and a lot of it isn't compatible DML or DDL for spanner.

**Comment by ChengyuanZhao** [comment]
Added awaiting tag because test won't actually complete since we need the statement.bind implementation. But i'm starting the work on bringing it over right now since that bind PR will be created shortly.

**Comment by ChengyuanZhao** [comment]
@elefeint I have a good idea now what to do :) I can take it from here
