### ISSUE TITLE
Fix javadoc errors

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-spanner-r2dbc#135]
Currently javadoc generation is turned on under the `release` profile. However, linting is turned off using ` <additionalparam>-Xdoclint:none</additionalparam>` because we have errors in our javadocs. 

We should fix javadoc issues and re-enable javadoc linting. Also, we should enable javadoc generation on Travis to verify that errors are not introduced in the future, after this is fixed.

**Comment by dzou** [comment]
Hey, could you explain how to generate the javadocs locally to produce the errors?

**Comment by meltsufin** [comment]
Simply remove `<additionalparam>-Xdoclint:none</additionalparam>` from `pom.xml`, and the run `package` with `-P release` profile.
