### ISSUE TITLE
Add integration test for reading and writing from real Spanner instance

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#14]
Something more polished than the [wip](https://github.com/elefeint/r2dbc-wip/blob/49cd39afccf7f83cb0c1682611cadcef517f884d/src/test/java/io/r2dbc/spanner/SampleSpannerTest.java#L86).

**Comment by ChengyuanZhao** [comment]
@elefeint  I was thinking of making a large table with columns of each type (including the array types) and then generating many rows of random data and doing LARGE reads so we can see many partial result sets in the result with chunks and then also trying out some insert /update /delete statements .

**Comment by elefeint** [comment]
Bonus points for data not being random, for easier troubleshooting.

**Comment by dzou** [comment]
Doing the large integration test will be useful for verifying our assumptions about partial result set contents. For example, I learned that the stats are actually provided in the last element emitted in the stream, not the first: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/issues/75#issuecomment-495764310
