### ISSUE TITLE
Implement keepalive option

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#141]
Spanner recommends to run a simple query (`SELECT 1`) periodically to avoid sessions being dropped.

The driver could do that as an optional feature, configured through connection properties.

**Comment by dzou** [comment]
Found this recently: https://github.com/googleapis/nodejs-spanner/issues/649

It was claimed that the GRPC client will shutdown after one hour of inactivity as well?

**Comment by elefeint** [comment]
It would be good to make it opt-out with configurable interval for keepalive.

**Comment by meltsufin** [comment]
We decided to instead rely on [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool) to implement keep-alive.
