### ISSUE TITLE
Consider tracking transaction state in Spanner Statement

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-r2dbc#150]
Determine whether or not the statement should check and save the active transaction on `statement.execute()`.

Context: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/146#discussion_r296899483

**Comment by ChengyuanZhao** [comment]
If I'm reading Mark's comment right:

"It's fair to say that any object associated with a transaction gets invalidated if the transaction gets committed. This is usual for SQL databases (e.g. close a result set when the transaction gets cleaned up or invalidate BLOB/CLOB objects after a transaction).

Does this help?"

He seems to say we should be throwing an exception if the results are actually consumed AFTER the commitTransaction call... ?

**Comment by dzou** [comment]
Hmm, he said the behavior is "undefined" which I guess would mean that we may handle it however we choose. So exception would be appropriate.

**Comment by elefeint** [comment]
Closing as obsolete. To summarize the discussion:
If `ResultSet.getRowsUpdated()` mono is consumed after transaction commits/rolls back, the behavior is up to the driver:
* if the driver happens to have cached the results from a previous run, it may return the results.
* if consuming the mono actually triggers the publisher chain with database-invoking functionality, this sequence of events is a user error and should cause an exception.
