### ISSUE TITLE
Propagate Error Status Code through Exceptions

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-r2dbc#154]
Currently, we are using `R2dbcTransientException` and `R2dbcNontransientException` to propagate exceptions to the user.

These exceptions do not contain error codes. So we would like to extend a new exception type which specifies transience but also propagate error codes to the user.

context: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/151#discussion_r298242609

**Comment by mp911de** [comment]
Related note: Duplicate rows are reported with `io.r2dbc.spi.R2dbcNonTransientResourceException: Row [42055] in table legoset already exists`, should be rather `R2dbcDataIntegrityViolationException`.
