### ISSUE TITLE
Make documentation code snippets testable

### ISSUE THREAD

**Issue by dmitry-s** [GoogleCloudPlatform/cloud-spanner-r2dbc#155]
This would probably require switching docs format to adoc.

**Comment by ttomsu** [comment]
Ack (since Dmitry isn't on the team anymore, this issue shows up as an external reporter and should be responded to).

**Comment by elefeint** [comment]
The samples are integration tested. Documentation is slowly shifting to markdown, which does not support importable code blocks.
