### ISSUE TITLE
Document the current isolation levels situation

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#166]
Cloud Spanner's isolation levels do not correspond to traditional relational database isolation levels. Spanner's default strong reads are roughly equivalent to READ_COMMITTED, REPEATABLE_READ and SERIALIZABLE enforced simultaneously (https://cloud.google.com/spanner/docs/true-time-external-consistency).

However, Spanner provides additional ability for stale-exact and stale-bounded isolation levels, which provide similar guarantees as of a point (or range) of time, but perform faster than strong reads.

**Comment by meltsufin** [comment]
Was the transaction mutability flag ever brought back to the spec?

**Comment by elefeint** [comment]
No, it's still at feature request stage -- r2dbc/r2dbc-spi#98.

**Comment by elefeint** [comment]
Closing this in favor of #249, so code and docs are done simultaneously.
