### ISSUE TITLE
Implement SpannerColumnMetadata.getJavaType()

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#206]
SPI recommends implementing this method; we've missed it.

**Comment by itssanjib** [comment]
@elefeint  I want to work on it. Could you please assign me.

**Comment by elefeint** [comment]
Yes, sorry for the late response.
Take a look at [DefaultCodecs](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/master/cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/codecs/DefaultCodecs.java) implementation and at how [H2 determines the Java type](https://github.com/r2dbc/r2dbc-h2/blob/37c73250a235874bb6204c13f51f04f1546a6eb1/src/main/java/io/r2dbc/h2/codecs/DefaultCodecs.java#L90) based on its default codecs.

**Comment by elefeint** [comment]
This still needs to be done for V2, but after the major components are implemented, so it should not be done right now.
