### ISSUE TITLE
Send driver version with metrics

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#216]
Currently the version is null, since we try to retrieve it as `GrpcClient.class.getPackage().getImplementationVersion()`, and no implementation version is available in manifest.

The task is to get Kokoro to add a manifest properly.

`0.1.0` release manifest:
```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: kbuilder
Created-By: Apache Maven 3.5.4
Build-Jdk: 1.8.0_201
```

**Comment by meltsufin** [comment]
See for example: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-core/src/main/java/org/springframework/cloud/gcp/core/UserAgentHeaderProvider.java#L62

**Comment by itssanjib** [comment]
I am new in the open source contribution. I am interested to  contribute for this issue.

**Comment by elefeint** [comment]
@itssanjib Welcome to Open Source! This particular issue requires some internal investigation; it might turn out to not be an issue at all.

If you'd like a good starter issue, take a look at #199 instead!
