### ISSUE TITLE
Support URL-based connection

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#30]
From Mark's [comment](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/26/files#r282182581) on #26:

```
There are two sides to configuration: Programmatic and URL-based. Both ways end up with providing a ConnectionFactoryOptions object.

Maybe you should start drawing of a R2DBC URL for Spanner would look like.

How about r2dbc:spanner:<project>//<instance>/<database>?

This way, <project> gets auto-propagated to ConnectionFactoryOptions.PROTOCOL, <instance> to HOST and <database> to DATABASE.
```

**Comment by meltsufin** [comment]
I'm not a fan of the project being mapped to `PROTOCOL`.

Since we can often infer the project ID, I would go with:
`r2dbc:spanner://<instance>/<database>?project=<project>`

**Comment by dzou** [comment]
For this, I think our url should follow the Spanner form for specifying qualified DB names: "projects/<project>/instances/<instance>/databases/<database_name>".

It is also how Knut's JDBC driver does it; and I think it would be useful if both the r2dbc and jdbc url formats were consistent: `jdbc:cloudspanner:/projects/my-project/instances/my-instance/databases/my-database`

`r2dbc:cloudspanner:/projects/<PROJECT>/instances/<INSTANCE>/databases/<DATABASE>`

**Comment by elefeint** [comment]
Additional information on how the connection string will be parsed in SPI: https://github.com/r2dbc/r2dbc-spi/pull/48

**Comment by elefeint** [comment]
The basic structure `ConnectionUrlParser` expects is `r2dbc:spanner://host:port/path`. We could likely shove the whole fully qualified Spanner path in the `path` section since a URL could have a path with multiple slash-separated sections, and leave `host` blank.

On the other hand, connection strings are for end users, and Spanner's fully qualified URL is quite verbose... So perhaps we could accept a terser `project/instance/database` format, or even use `projectId` to represent `host`.

So, some options that should work (but I have not tested them):
* `r2dbc:spanner:///projects/my-project/instances/my-instance/databases/my-database` 
  * host: null, path: `projects/my-project/instances/my-instance/databases/my-database`
* `r2dbc:spanner:///my-instance/my-database`
  * host: null, path: `my-project/my-instance/my-database`
* `r2dbc:spanner://my-project/my-instance/my-database`
  * host: `my-project`, path: `my-instance/my-database`)

**Comment by elefeint** [comment]
Decided on using Spanner gRPC url as authority:
`r2dbc:spanner://spanner.googleapis.com:443/projects/my-project/instances/my-instance/databases/my-database`

**Comment by elefeint** [comment]
And to use a default if authority is missing (unless r2dbc URL parsing complains about this -- verify)
