### ISSUE TITLE
v2 DML operation not triggered by Spring Data

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#346]
Testing a trivial insert works in v1, but does not trigger the asynchronous operation in v2.

```
  @PostMapping("/add")
  public Mono<Void> addBook(@RequestBody String bookTitle) {
    return r2dbcEntityTemplate.insert(Book.class)
        .using(new Book(UUID.randomUUID().toString(), bookTitle))
        .then();
  }
```

[This code](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/403156d2f12dc792c870f03d1920c689cc594cf5/cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/SpannerClientLibraryDmlStatement.java#L51-L52) in Spanner R2DBC driver v2 causes the issue. Spring Data R2DBC subscribes to the outer `Mono<Result>`, but never subscribes to the inner `Mono` representing number of updated rows.

**Comment by elefeint** [comment]
@mp911de I may have misinterpreted [the javadoc for `Result` class](https://github.com/r2dbc/r2dbc-spi/blob/8de2fd017366254602a185987130ba8955340644/r2dbc-spi/src/main/java/io/r2dbc/spi/Result.java#L24). It says: 

>  Results can be consumed only once by either consuming {@link #getRowsUpdated()} or {@link #map(BiFunction)}

But it seems that it's valid for Spring Data to call *neither* of those, and still expect the operation to have completed. Is it true, then, that by the time a `Result` object exists, the operation is expected to have triggered?

**Comment by mp911de** [comment]
R2DBC results must be consumed to ensure that the backing stream of data gets consumed. If Spring Data R2DBC doesn't call either method, then this is a bug.

The insert method specifically assumes a single result. So if you emit multiple `Result`s, then this is somewhat unexpected (as per spec it's fine to do so).

**Comment by elefeint** [comment]
@mp911de  I see what happens. Spring Data's `R2dbcEntityTemplate.doInsert()` calls  `DefaultFetchSpec.all()`, not `DefaultFetchSpec.rowsUpdated()`. So on the driver level, `Result.map()` is called to consume any available generated values, and `Result.getRowsUpdated()` is never called. 

This seems intentional on Spring Data level, so the solution will be for the Cloud Spanner driver to stop assuming that `getRowsUpdated()` will be called for DML.

**Comment by mp911de** [comment]
We're consuming rows assuming generated identifiers that we can feedback into the inserted entity.
