### ISSUE TITLE
Retry aborted commits

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#36]
From Spanner [commit docs](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.v1#google.spanner.v1.Spanner.Commit):

> Commit might return an ABORTED error. This can occur at any time; commonly, the cause is conflicts with concurrent transactions. However, it can also happen for a variety of other reasons. If Commit returns ABORTED, the caller should re-attempt the transaction from the beginning, re-using the same session.

**Comment by dzou** [comment]
Notes:
- Looks like transactions must be repeated from beginning based on responses here: https://stackoverflow.com/questions/56118837/how-to-retry-spanner-commits-that-were-aborted/

- Client library uses concept of `resetForRetry` [to reset the transaction](https://github.com/googleapis/google-cloud-java/blob/be7ece53c3f25fc81fa31fa0675e0a8f38d442d0/google-cloud-clients/google-cloud-spanner/src/main/java/com/google/cloud/spanner/TransactionManagerImpl.java#L89). It doesn't look like they actually replay the statements run in the transaction.

**Comment by meltsufin** [comment]
So the client library just ignores the commit failure?
I think it might be OK to just ignore it as well, and the application code would have to retry.

**Comment by dzou** [comment]
Gotcha. Yeah seems so. The client library asks users to call this [resetForRetry](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/spanner/TransactionManager.html#resetForRetry--) method:

>Creates a new transaction for retry. This should only be called if the previous transaction failed with ABORTED . In all other cases, this will throw an IllegalStateException . Users should backoff before calling this method. Backoff delay is specified by SpannerException.getRetryDelayInMillis() on the SpannerException throw by the previous commit call.

Seems like they are delegating to the user to call `resetForRetry` and retry on their own if the transaction fails.

**Comment by dzou** [comment]
Client library actually does both.

1. Transactions that are run via `TransactionRunner.run(TransactionCallable c)` are retried:
https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/spanner/TransactionRunner.html#run-com.google.cloud.spanner.TransactionRunner.TransactionCallable-

> Executes a read-write transaction, with retries as necessary. The work to perform in each transaction attempt is defined by callable , which may return an object as the result of the work. callable will be retried if a transaction attempt aborts; implementations must be prepared to be called more than once. Any writes buffered by callable will only be applied if the transaction commits successfully. Similarly, the value produced by callable will only be returned by this method if the transaction commits successfully.

2. Transactions run with `TransactionManager` are not retried and one must run `resetForRetry()` if the `commit()` gets aborted.

> Creates a new transaction for retry. This should only be called if the previous transaction failed with ABORTED . In all other cases, this will throw an IllegalStateException . Users should backoff before calling this method. Backoff delay is specified by SpannerException.getRetryDelayInMillis() on the SpannerException throw by the previous commit call.

https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/spanner/TransactionManager.html#resetForRetry--

**Comment by olavloite** [comment]
The client library offers two options of handling ABORTED transactions:
1. Transactions that are run via `TransactionRunner.run(TransactionCallable c)` are retried by the client library automatically, and tries to hide as much of the complexity from the user as possible. This method is intended for most users that work directly with the client library (i.e. are not writing another client library on top of the Spanner client library).

2. Transactions run with TransactionManager are not automatically retried and one must run resetForRetry() if the transaction is aborted. This method is intended for advanced users who want to be able to handle the retry logic themselves. As mentioned above, the entire transaction must be re-run when a transaction is aborted. Also note that **any database call could return an ABORTED error**. It is not only the `commit()` that could abort, but any query or update could return an ABORTED error. Your retry logic should therefore always check for this condition on every database call and restart the transaction if it happens.

On a gRPC level, a transaction retry is really nothing else than a new transaction. The method `resetForRetry()` of the client library doesn't call some special method server side. It just starts a new transaction.

**Comment by dzou** [comment]
Closing this issue. We discussed with R2DBC folks and they recommended propagating all errors down to the end user (even transient network errors). If we decide that things change regarding retries in the future, we may revisit.
