### ISSUE TITLE
Extend SpannerConnection to support multiple transaction types

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-r2dbc#40]
Currently `SpannerConnection` defaults to using read-write transactions.

Extend it to support `read-only` and `partitioned DML` transactions.

**Comment by elefeint** [comment]
NB: partitioned DML transactions don't need to be committed (don't support commit or rollback).

**Comment by dzou** [comment]
From the master design doc:

> The SPI supports isolation level specification on the Connection, but Cloud Spanner just has two types of transactions read-only and read-write, which don’t map into the isolation levels.
The decision is to allow configuring the default transaction mutability on the ConnectionFactory as well as overloading the beginTrasaction(mutability) method in the SpannerConnection class. In the future, the R2DBC SPI may support the transaction mutability setting natively.

**Comment by dzou** [comment]
This one is a little bit unusual; on further experimentation, it appears that it is invalid to call `CommitTransaction` on a read-only or partitioned DML transaction. Currently I'm thinking of just doing a no-op commit if user attempts to call commit in either context.

**Comment by ChengyuanZhao** [comment]
looks like this was completed in #109
