### ISSUE TITLE
Consider if Codecs should support more flexible decoding conversions

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-r2dbc#47]
Consider if the Codecs should support conversions that are logical. Things like:

- Allowing encoding Java `Integer` type to Spanner INT64 type.
- Allow for most Spanner types with toString representation to convert back to Java String (INT64, BOOL, etc.)

**Comment by dmitry-s** [comment]
@dzou 
Actually, we support Integer to INT64 conversion already.

**Comment by elefeint** [comment]
Fixed as part of #105
