### ISSUE TITLE
Binding List<String> in Kotlin

### ISSUE THREAD

**Issue by SereiaMaster** [GoogleCloudPlatform/cloud-spanner-r2dbc#481]
I verified in the documentation that to bind an array, we must use the primitive type.
But in Kotlin, we don't have the primitive type. Only Collections or Lists.

How to make the Bind for these cases?

`{
    "details": "Error id a1517f8b-61e1-4013-8d44-ecc76480910c-1, com.google.cloud.spanner.r2dbc.BindingFailureException: Can't find a binder for type: class java.util.Arrays$ArrayList",
    "stack": "com.google.cloud.spanner.r2dbc.BindingFailureException: Can't find a binder for type: class java.util.Arrays$ArrayList\r\n\tat com.google.cloud.spanner.r2dbc.v2.ClientLibraryBinder.bind(ClientLibraryBinder.java:72)\r\n\tat com.google.cloud.spanner.r2dbc.v2.AbstractSpannerClientLibraryStatement.bind(AbstractSpannerClientLibraryStatement.java:113)\r\n\tat io.r2dbc.client.Query.bind(Query.java:60)\r\n\tat br.inf.cerc.repository.v15.CompanyRepository.findByEmail$lambda-2(CompanyRepository.kt:26)\r\n\tat io.r2dbc.client.R2dbc.lambda$withHandle$2(R2dbc.java:123)\r\n\tat reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:163)\r\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)\r\n\tat reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)\r\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)\r\n\tat reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:141)\r\n\tat reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)\r\n\tat reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)\r\n\tat reactor.core.publisher.Flux.subscribe(Flux.java:8469)\r\n\tat io.smallrye.mutiny.groups.MultiCreate$2.subscribe(MultiCreate.java:190)\r\n\tat io.smallrye.mutiny.operators.AbstractMulti.subscribe(AbstractMulti.java:26)\r\n\tat io.smallrye.mutiny.groups.MultiSubscribe.withSubscriber(MultiSubscribe.java:70)\r\n\tat io.smallrye.mutiny.operators.multi.MultiSubscribeOnOp$SubscribeOnProcessor.lambda$scheduleSubscription$1(MultiSubscribeOnOp.java:78)\r\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)\r\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)\r\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:829)"
}`

**Comment by chanseokoh** [comment]
I don't think Kotlin is the problem. According to the [code](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/3baf3b1d4c4bda81fff4aa8fae062bda074a92e8/cloud-spanner-r2dbc/src/main/java/com/google/cloud/spanner/r2dbc/v2/ClientLibraryBinder.java#L36-L55), there's no binder for a list or array at all.

**Comment by elefeint** [comment]
That's right; this is a half-missing feature. _Reading_ Spanner arrays into Java lists is supported, but writing anything into Spanner arrays is not. 

I'll try to get it in this week.

**Comment by elefeint** [comment]
After looking at it, I see why this part was not done initially -- Spanner has typed arrays, but R2DBC specification binding accepts an Object, which means parameterization is lost.

However! The latest specification of R2DBC has advanced typed bindings, and since upgrading the spec was on top of our priority list for the driver, this is a great place to start.
