### ISSUE TITLE
Replace blocking with StepVerifier in tests

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#55]
Step verifier is more flexible, and will lead to more readable tests as the tests get more complex.

https://projectreactor.io/docs/core/release/reference/#_testing_a_scenario_with_stepverifier
https://projectreactor.io/docs/test/release/api/reactor/test/StepVerifier.html

**Comment by JoeWang1127** [comment]
close as not planned
