### ISSUE TITLE
Info on future maintenance of this library

### ISSUE THREAD

**Issue by girish-jung** [GoogleCloudPlatform/cloud-spanner-r2dbc#608]
Hi Team, 

I am new to GCP Cloud Spanner and planning to use "**com.google.cloud:cloud-spanner-spring-data-r2dbc**" in our project. 
I see that the last version of this library was published an year back. 
So i was wondering if you are still planing to future develop and maintain this in the future with new feature and keeping it up to date.

Thanks
Girish Jung

**Comment by girish-jung** [comment]
When are we releasing v1.20 for this.. I see that some development has already happened... 
Currently v1.1.0 is not compatible with google-cloud-spanner v1.19.0 or higher

**Comment by meltsufin** [comment]
v1.2.0 has just been [released](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/releases/tag/v1.2.0).

**Comment by girish-jung** [comment]
nice.. it got release almost at the same time i intend to use it....  Thanks @meltsufin

**Comment by girish-jung** [comment]
Any idea how long does it take for it to be available on mvn repo.. 
https://mvnrepository.com/artifact/com.google.cloud/cloud-spanner-r2dbc

**Comment by meltsufin** [comment]
It's already on Maven Central: https://repo.maven.apache.org/maven2/com/google/cloud/cloud-spanner-r2dbc/1.2.0/.
Mvnrepository.com has a delay in its update, but you should be able to use it from your project. Please let us know if you encounter any issues.
