### ISSUE TITLE
Context loss after applying com.google.cloud.spanner.r2dbc.v2.SpannerClientLibraryStatement

### ISSUE THREAD

**Issue by filipenfst** [GoogleCloudPlatform/cloud-spanner-r2dbc#685]
When i enable automatic context propagation and context lost tracking and i call `CoroutineCrudRepository.findAll()` i get the error `Context loss after applying com.google.cloud.spanner.r2dbc.v2.SpannerClientLibraryStatement$$Lambda$1889/0x000000080176c0e0@19574274`

The issue can be reproduced on the test `contextLostTest` that you can find here https://github.com/filipenfst/spanner-context-error/blob/master/src/test/kotlin/com/example/spannercontexterror/R2DBCSpannerErrors.kt

The issue can be fixed by propagating the context to the rows like this
```
  @Override
  protected Mono<SpannerClientLibraryResult> executeSingle(Statement statement) {
    return this.clientLibraryAdapter
        .runSelectStatement(statement)
        .transform(rows -> {
          return Mono.deferContextual(c -> {
            return Mono.just(new SpannerClientLibraryResult(rows.contextWrite(c), 0));
          });
        }).single();
  }
````

**Comment by filipenfst** [comment]
I cant down grade the spring boot because i need some features that are only available on Spring boot 3.

**Comment by meltsufin** [comment]
I guess there is a separate request to support Spring Boot 3. Nonetheless, I'm curious if this issue exists in the current codebase, when using Spring Boot 2.7.

**Comment by meltsufin** [comment]
It's in the release notes: https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/releases
