### ISSUE TITLE
asserts are not working

### ISSUE THREAD

**Issue by eddumelendez** [GoogleCloudPlatform/cloud-spanner-r2dbc#70]
I moved these asserts and the tests are failing.

```java
assertThat(columnMetadata).isEqualTo(results.get(0).getRowMetadata().getColumnMetadatas());
    assertThat(columnMetadata).isEqualTo(results.get(1).getRowMetadata().getColumnMetadatas());
```

https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/blob/c84f0305777253f855865145aee3ecc3a8db0d18/src/test/java/com/google/cloud/spanner/r2dbc/result/PartialResultRowExtractorTest.java#L199-L202

**Comment by dzou** [comment]
Can you post the errors that you see?

In the updated version of the asserts, it doesn't look like you added a suffix to the assertThat clause. `assertThat(...)` will throw an error if you call an `assertThat(...)` without a suffix such as `.isEqualTo(...)` or `isTrue(...)`, etc.

**Comment by eddumelendez** [comment]
> Can you post the errors that you see?

```
org.junit.ComparisonFailure: 
<Click to see difference>


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.google.cloud.spanner.r2dbc.result.PartialResultRowExtractorTest.verifyRows(PartialResultRowExtractorTest.java:199)
	at com.google.cloud.spanner.r2dbc.result.PartialResultRowExtractorTest.assembleRowsTest(PartialResultRowExtractorTest.java:120)
```

<img width="1479" alt="Screen Shot 2019-05-22 at 17 38 36" src="https://user-images.githubusercontent.com/1810547/58213621-b3d56480-7ca7-11e9-9216-aede0065f105.png">

`asserThat` is from `assertj` so the suffix is required to perform the validation. If we look closely to the current assertions they do not have it. These asserts are valid?

**Comment by dzou** [comment]
Ah I see, that is indeed a mistake on our side. I can take a look at it.

**Comment by ChengyuanZhao** [comment]
@dzou  is this actually an error? 

That screenshot simply says those objects are not the same instances , but they are the same objects in terms of value and contents.

**Comment by dzou** [comment]
I'm just looking at the assert statement itself, I'm unsure if its written correctly.

The line:
```
assertThat( 
     Objects.areEqual(columnMetadata, results.get(0).getRowMetadata().getColumnMetadatas()));
```

Should be:
```
assertThat( 
     Objects.areEqual(columnMetadata, results.get(0).getRowMetadata().getColumnMetadatas()));
.isTrue()
```

I don't think the assertion does anything without the `.isTrue()`... at least that is how it works in the Google Truth library; unsure about AssertJ.
