### ISSUE TITLE
Parameter validation on bind

### ISSUE THREAD

**Issue by dmitry-s** [GoogleCloudPlatform/cloud-spanner-r2dbc#74]
The r2dbc-spi [docs](https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spec/src/main/asciidoc/statements.adoc) say 

> The method used to execute a parameterized Statement an IllegalStateException if a value is not supplied for a bind marker.

The sentence is incomplete. @mp911de could you clarify if we should check that on our side or is it optional?

Thanks

**Comment by ChengyuanZhao** [comment]
related to #13

**Comment by mp911de** [comment]
Good catch. The spec should be: The `execute` method used to execute a parameterized `Statement` throws an `IllegalStateException` if a value is not supplied for a bind marker.

The javadoc on `Statement.execute` already reflects the specification: `@throws IllegalStateException if the statement is parametrized and not all parameter values are provided`.

**Comment by ChengyuanZhao** [comment]
@dmitry-s If you were to try running a query with an un-filled tag then Spanner will give you the error and you can just wrap that in an IllegalStateException as required by r2dbc.

**Comment by elefeint** [comment]
Decided not to handle this for Spanner.
