### ISSUE TITLE
Faililng Sonar Cloud GH Action keeps emailing me

### ISSUE THREAD

**Issue by ttomsu** [GoogleCloudPlatform/cloud-spanner-r2dbc#770]
Once in a blue moon ago, I helped set up the Sonar cloud analysis. Now it appears to be failing daily and emailing me about it. I no longer have permissions to this repo to see if there is something in Settings to make it stop - so.... can someone like @meltsufin take a look?

https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/actions/workflows/sonar.yaml

Thank you!

**Comment by meltsufin** [comment]
Hey Travis! I think this is because you are the last committer to the file.
@suztomo Can you please take a look at the issue with this workflow. It looks like we just need to upgrade the JDK version.

**Comment by suztomo** [comment]
Checking...

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project cloud-spanner-r2dbc-parent: 
Error:  
Error:  The version of Java (11.0.22) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
Error:  As a temporary measure, you can set the property 'sonar.scanner.force-deprecated-java-version' to 'true' to continue using Java 11.0.22
Error:  This workaround will only be effective until January 28, 2024. After this date, all scans using the deprecated Java 11 will fail.
```

**Comment by suztomo** [comment]
https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/actions/runs/7628448005 succeeded and I'm the last one who edited the file.
