### ISSUE TITLE
Investigate Compatibility between Spanner R2DBC with Spring Data R2DBC

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/cloud-spanner-r2dbc#84]

**Comment by dzou** [comment]
Initial steps looks to be creation and registration of a R2DBC dialect:

See: 

1. R2dbcDialect Class https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/dialect/R2dbcDialect.java
2. Contains impls of r2dbc dialect: https://github.com/spring-projects/spring-data-r2dbc/tree/master/src/main/java/org/springframework/data/r2dbc/dialect

**Comment by meltsufin** [comment]
I looked at some dialects there and they seem pretty trivial. Less than <100 lines of code.

**Comment by dzou** [comment]
I created a branch with the setup and dialect necessary to support spring data r2dbc.

Compatibility is confirmed. #89

**Comment by elefeint** [comment]
Now that the driver is published in sonatype nexus, the code can be moved to `spring-cloud-gcp`.
