### ISSUE TITLE
Support DDL

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/cloud-spanner-r2dbc#88]
In Cloud Spanner, DDL statements are processed through a different API than SQL and DML.
See: [spanner_database_admin.proto](https://github.com/googleapis/google-cloud-java/blob/master/google-api-grpc/proto-google-cloud-spanner-admin-database-v1/src/main/proto/google/spanner/admin/database/v1/spanner_database_admin.proto)

**Comment by ChengyuanZhao** [comment]
Is the goal to use the same Statement type to run DDL ? 

I'm not sure the r2dbc spec had that in mind: https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spec/src/main/asciidoc/statements.adoc

Furthermore,  their tests specifically use an external thing to run the DDL : https://github.com/r2dbc/r2dbc-spi/blob/master/r2dbc-spi-test/src/main/java/io/r2dbc/spi/test/Example.java

I don't think they expected to use DDL inside R2DBC. Besides, while DML and SQL may happen arbitrary number of times in normal usage I think DML (creating deleting tables) is inherently an offline task right?

**Comment by elefeint** [comment]
Hmm, perhaps that's right. In SPI tests, the DDL operations are done outside of the reactive logic by [getting hold of a separate JDBC template](https://github.com/r2dbc/r2dbc-spi/blob/966a228cc8df50aaa26f60b61a31b20ffb4628f9/r2dbc-spi-test/src/main/java/io/r2dbc/spi/test/Example.java#L370).

@mp911de Mark -- could you confirm whether R2DBC was meant to support DDL?

**Comment by mp911de** [comment]
R2DBC's `Connection.createStatement(…)` should be able to run any kind of queries, similar to how JDBC's `Statement.execute()` may run any kind of statements.

We're using `JdbcTemplate` in the SPi tests because it does not require the synchronization dance of reactive APIs.

**Comment by elefeint** [comment]
Good to know, thank you!

Cloud Spanner is a bit unusual in that it does not provide a single API to run any generic query through, so we'll have to do query detection in the driver. I've filed #92 to track doing so for DML, and this issue will track the DDL side.

**Comment by mp911de** [comment]
I'd suggest sticking with what your JDBC driver does in most cases. R2DBC is in a lot of ways similar to what JDBC does.

**Comment by ChengyuanZhao** [comment]
closing, this was done in #106
