### ISSUE TITLE
Decide what to do with position-based param binding

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/cloud-spanner-r2dbc#91]
Currently we do not support binding params by position since Spanner SQL does not support tags for position. We currently do not want to alter users' SQL.

**Comment by dzou** [comment]
From past discussions with Mark, it sounded like they did some mild parsing of named `@` bind variables and then computed the index of the correct variable to use through parsing. This could be one approach we take.

**Comment by ChengyuanZhao** [comment]
I think we're all just concerned mild parsing can easily turn into mild-to-moderate or even moderate parsing

**Comment by elefeint** [comment]
Decided not to handle this for Spanner.
