### ISSUE TITLE
Handle dropped Sessions

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/cloud-spanner-r2dbc#96]
Spanner can drop sessions, so Connection should be able to recreate a session on a failed action. 
Figure out if the failed action should be retried on a stale session.

Spanner also recommends [sending keepalive queries](https://cloud.google.com/spanner/docs/sessions#keep_an_idle_session_alive), so perhaps that should be a default + connection setting.

**Comment by dzou** [comment]
So looking at this a little bit, looks like Spanner throws a special exception like 'Session not found' Exception when the session no longer exists. Based on client library code, when the session is dropped it will trigger the `SessionNotFoundException` if the user tries to reference it.

But then seeing it this way, it kind of seems like this case collapses as a special case of "retry logic". I.e. if the exception is thrown, the session should be restarted and query should be retried. In light of this, does it make sense to just delegate dropped session exceptions to the user? (Just like how we delegate handling transient RPC errors to users).

**Comment by meltsufin** [comment]
What does the JDBC driver do?

**Comment by dzou** [comment]
I don't think the JDBC handles sessions because it uses the client library, and the client library hides the session details from the client library consumer.

**Comment by meltsufin** [comment]
Then I guess the answer is that it just throws the exception to the client?

**Comment by dzou** [comment]
Reopening - based on discussions in #140, we may elect to implement built-in restart-session logic.

**Comment by elefeint** [comment]
Closing as obsolete; V2 relies on client library, which handles reconnections and session pools.
