### ISSUE TITLE
Storing Transaction instead of a Mono of Transaction causes some issues

### ISSUE THREAD

**Issue by ChengyuanZhao** [GoogleCloudPlatform/cloud-spanner-r2dbc#98]
see #97 

One of the TCK tests ( "tranactionCommit()" ) begins a transaction and then follows it up with thenMany, but it seems the following operations try to use the transaction when it isn't set yet.

**Comment by elefeint** [comment]
I'm thinking of renaming TransactionContext to ExecutionContext, and stuffing the session ID in it, too.
